"use client";

import React, { useRef, useCallback, useEffect } from "react";
import IntlTelInput from "intl-tel-input/react";
import "intl-tel-input/build/css/intlTelInput.css";
import type { IntlTelInputRef } from "intl-tel-input/react";
import type { Iso2 } from "intl-tel-input/data";
import {
  DEFAULT_COUNTRY,
  isSupportedCountry,
  resolveSupportedCountry,
} from "./supportedCountries";
import { useDialogPortalEventIsolation } from "@/hooks/useDialogPortalEventIsolation";

/**
 * PhoneInput - Wrapper around intl-tel-input for international phone number input.
 *
 * Replaces the custom phoneFormatter system with a fully-featured library that
 * covers 200+ countries out of the box.
 *
 * Features:
 * - Country flag dropdown with search
 * - Automatic country detection from phone number
 * - Country-specific validation via libphonenumber
 * - separateDialCode mode shows dial code beside input
 * - strictMode blocks invalid characters and caps at max valid length
 * - Outputs raw digits (no formatting chars) for form submission
 *
 * @module components/ui/phone-input/PhoneInput
 */

export interface PhoneInputProps {
  /** Field value (raw digits, no formatting) */
  value?: string;
  /** Called with raw digits whenever the phone number changes */
  onChange: (value: string) => void;
  /** Called on blur */
  onBlur?: () => void;
  /** Initial country (ISO 3166-1 alpha-2 lowercase, e.g. "us", "gb") */
  initialCountry?: string;
  /** HTML id attribute */
  id?: string;
  /** Placeholder text (auto-generated by library if not provided) */
  placeholder?: string;
  /** Whether the input is disabled */
  disabled?: boolean;
  /** Whether the input has an error */
  error?: boolean;
  /** Whether the field is required */
  required?: boolean;
  /** CSS class name for the input element */
  className?: string;
  /** Called when the selected country changes (uppercase ISO2, e.g. "US") */
  onCountryChange?: (countryIso2: string) => void;
  /**
   * Restrict the country dropdown to these ISO2 codes (lowercase, e.g. ["us"]).
   * Use for forms whose other fields are locked to specific countries so an
   * out-of-scope national number can't be entered.
   */
  onlyCountries?: string[];
  /**
   * Set false to hide the country dropdown entirely — the flag/dial code stays
   * visible but fixed to `initialCountry`. Defaults to true (library default).
   */
  allowDropdown?: boolean;
}

/**
 * PhoneInput component integrating intl-tel-input with react-hook-form.
 *
 * The component stores raw digits in the form state (no formatting chars),
 * matching existing server-side expectations in card-provisioning-service.
 */
const PhoneInput: React.FC<PhoneInputProps> = ({
  value = "",
  onChange,
  onBlur,
  initialCountry = DEFAULT_COUNTRY,
  id,
  placeholder,
  disabled = false,
  error = false,
  required = false,
  className,
  onCountryChange,
  onlyCountries,
  allowDropdown,
}) => {
  // intl-tel-input only ships data for ~244 countries, but the country dropdowns
  // are built from country-list (249). Resolve to a code the library supports so
  // its public setCountry()/initOptions never receive an unknown code (which
  // throws "Invalid country code: '<code>'" and crashes the form).
  const safeInitialCountry = resolveSupportedCountry(initialCountry);

  const itiRef = useRef<IntlTelInputRef | null>(null);
  const valueRef = useRef<string>(value);
  const selectedIso2Ref = useRef<string>(safeInitialCountry);
  const hasInteractedRef = useRef<boolean>(false);
  const manualCountrySelectionRef = useRef<boolean>(false);
  const manualSelectionResetTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  // intl-tel-input emits one country change on mount. When we substitute a
  // supported fallback for an unsupported initialCountry, that single mount echo
  // must be swallowed (see handleCountryChange). This is consumed on the first
  // emission so any later genuine selection — even of the fallback country
  // itself — still propagates. A fresh instance per mount is correct because
  // DynamicForm remounts PhoneInput whenever initialCountry changes (keyed prop).
  const pendingMountFallbackEchoRef = useRef<boolean>(true);

  const getInputElement = useCallback((): HTMLInputElement | null => {
    const fromRef = itiRef.current?.getInput();
    if (fromRef) return fromRef;
    if (typeof document === "undefined" || !id) return null;
    const byId = document.getElementById(id);
    return byId instanceof HTMLInputElement ? byId : null;
  }, [id]);

  const markManualCountrySelection = useCallback(() => {
    manualCountrySelectionRef.current = true;
    if (manualSelectionResetTimerRef.current !== null) {
      clearTimeout(manualSelectionResetTimerRef.current);
    }
    manualSelectionResetTimerRef.current = setTimeout(() => {
      manualCountrySelectionRef.current = false;
      manualSelectionResetTimerRef.current = null;
    }, 300);
  }, []);

  // onChangeNumber receives the result of the library's getNumber(), which
  // always returns E.164 (full international, dial code included) regardless of
  // nationalMode/separateDialCode — those options only affect display/parsing.
  // So we strip the selected country's dial code below to emit national digits,
  // matching the server's national-digit expectations.
  const handleNumberChange = useCallback(
    (number: string) => {
      // intl-tel-input can emit an initial empty change during mount/formatting.
      // Ignore only that specific non-interactive emission so forms do not show
      // phone validation errors on mount.
      if (!hasInteractedRef.current && !number && !valueRef.current) {
        return;
      }

      const rawDigits = number.replace(/\D/g, "");

      // Guard: if the library instance isn't ready yet, pass raw digits through.
      // In nationalMode the value is already in national format so this is safe.
      const instance = itiRef.current?.getInstance();
      if (!instance) {
        onChange(rawDigits);
        return;
      }

      const countryData = instance.getSelectedCountryData();
      const dialCode = countryData?.dialCode || "";

      // Remove the dial code prefix to get local digits only.
      // This matches existing server expectations in card-provisioning-service.
      let localDigits = rawDigits;
      if (dialCode && rawDigits.startsWith(dialCode)) {
        localDigits = rawDigits.slice(dialCode.length);
      }

      // Keep country stable while typing: intl-tel-input can auto-detect and
      // switch countries based on entered digits, which can desync form country
      // and create unexpected UX. Revert any auto-switch to the current selected
      // country tracked in selectedIso2Ref.
      const currentIso2 = instance.getSelectedCountryData()?.iso2?.toLowerCase();
      const lockedIso2 = selectedIso2Ref.current;
      if (
        currentIso2 &&
        lockedIso2 &&
        currentIso2 !== lockedIso2 &&
        typeof instance.setCountry === "function"
      ) {
        instance.setCountry(lockedIso2 as Iso2);
      }

      onChange(localDigits);
    },
    [onChange]
  );

  useEffect(() => {
    valueRef.current = value;
  }, [value]);

  // Sync external form resets to intl-tel-input's internal DOM.
  // intl-tel-input uses `initialValue` (uncontrolled) so react-hook-form's
  // reset() updates form state to "" but the library input keeps the old number.
  // When value is reset to "" we imperatively clear the input via the instance.
  useEffect(() => {
    if (value !== "") return;

    const inputEl = getInputElement();
    if (!inputEl || !inputEl.value) return; // already empty, nothing to do

    // Reset the interaction flag so the mount-time empty-emission guard works
    // correctly if the form is reused without unmounting.
    hasInteractedRef.current = false;

    // Clear the DOM input directly — do NOT use instance.setNumber("") here.
    // setNumber fires onChangeNumber → onChange → setValue({ shouldValidate: true })
    // which re-triggers Zod validation on the now-empty field and surfaces an
    // error immediately after a successful submit reset.
    inputEl.value = "";

    // Restore the flag dropdown to the initial country so the empty input and
    // the flag are in sync (e.g. user picked UK, submitted, flag resets to US).
    const instance = itiRef.current?.getInstance();
    const targetIso2 = resolveSupportedCountry(initialCountry);
    if (instance && typeof instance.setCountry === "function") {
      instance.setCountry(targetIso2 as Iso2);
    }
    selectedIso2Ref.current = targetIso2;
  }, [value, getInputElement, initialCountry]);

  // Remove title attribute from the intl-tel-input flag button.
  // intl-tel-input sets title="<CountryName>: +<dialCode>" on the flag button,
  // which renders as a browser tooltip on hover and duplicates the country name
  // already visible in the Country select field.
  const removeFlagTitle = useCallback(() => {
    const inputEl = getInputElement();
    if (!inputEl) return;
    const flagBtn = inputEl.closest(".iti")?.querySelector(".iti__selected-country");
    if (flagBtn) (flagBtn as HTMLElement).removeAttribute("title");
  }, [getInputElement]);

  // onChangeCountry receives the country ISO2 string
  const handleCountryChange = useCallback(
    (countryIso2: string) => {
      if (!countryIso2) {
        removeFlagTitle();
        return;
      }

      // Consume the one-shot mount-echo flag on the FIRST non-empty emission,
      // regardless of which branch handles it. intl-tel-input fires its mount
      // emission asynchronously (behind loadUtils), so the user may already be
      // typing when it arrives — consuming here, not only in the else branch,
      // keeps "first emission" unambiguous.
      const wasPendingMountEcho = pendingMountFallbackEchoRef.current;
      pendingMountFallbackEchoRef.current = false;

      const iso2Lower = countryIso2.toLowerCase();
      const inputEl = getInputElement();
      const isTypingInInput = !!inputEl && document.activeElement === inputEl;
      const isTypingContext = isTypingInInput || hasInteractedRef.current;
      const isManualSelection = manualCountrySelectionRef.current;

      // Ignore countrychange events emitted while typing when they are not
      // explicit user selections (auto-detection side effects).
      if (isTypingContext && !isManualSelection) {
        const instance = itiRef.current?.getInstance();
        const lockedIso2 = selectedIso2Ref.current;
        if (
          instance &&
          lockedIso2 &&
          iso2Lower !== lockedIso2 &&
          typeof instance.setCountry === "function"
        ) {
          instance.setCountry(lockedIso2 as Iso2);
        }
      } else {
        selectedIso2Ref.current = iso2Lower;
        // Swallow ONLY the automatic mount-time echo of a fallback we substituted
        // for an unsupported initialCountry (e.g. PN→us). Propagating it would
        // silently overwrite the user's real country in forms that persist
        // onCountryChange (e.g. invite/add payee). The automatic echo is always the
        // FIRST emission (the library sets the initial country at init), so we key
        // off the one-shot flag alone: any later genuine selection — including
        // manually re-picking the fallback country itself — has the flag already
        // consumed and therefore propagates. (We deliberately do NOT use the
        // manual-selection latch here: it is a coarse 300ms timer set merely by
        // opening the dropdown, which would let the automatic echo through if it
        // raced the user opening the flag menu.)
        const isMountFallbackEcho =
          wasPendingMountEcho &&
          !isSupportedCountry(initialCountry) &&
          iso2Lower === safeInitialCountry;
        if (onCountryChange && !isMountFallbackEcho) {
          onCountryChange(iso2Lower.toUpperCase());
        }
      }

      // intl-tel-input resets the title after each country change — remove it again
      removeFlagTitle();
    },
    [getInputElement, onCountryChange, removeFlagTitle, initialCountry, safeInitialCountry]
  );

  useEffect(() => {
    const nextIso2 = resolveSupportedCountry(initialCountry);
    selectedIso2Ref.current = nextIso2;

    const instance = itiRef.current?.getInstance();
    const currentIso2 = instance?.getSelectedCountryData()?.iso2?.toLowerCase();
    if (instance && currentIso2 !== nextIso2 && typeof instance.setCountry === "function") {
      instance.setCountry(nextIso2 as Iso2);
    }
  }, [initialCountry]);

  // Track explicit user country selection interactions (flag button, country list,
  // keyboard selection) so we can distinguish them from typing-triggered
  // auto-detection country changes.
  useEffect(() => {
    const inputEl = getInputElement();
    if (!inputEl) return;

    const markInteracted = () => {
      hasInteractedRef.current = true;
    };

    inputEl.addEventListener("focus", markInteracted);
    inputEl.addEventListener("input", markInteracted);
    inputEl.addEventListener("change", markInteracted);

    return () => {
      inputEl.removeEventListener("focus", markInteracted);
      inputEl.removeEventListener("input", markInteracted);
      inputEl.removeEventListener("change", markInteracted);
    };
  }, [getInputElement]);

  useEffect(() => {
    const handlePointerDown = (event: Event) => {
      const target = event.target as HTMLElement | null;
      if (!target) return;
      if (
        target.closest(".iti__selected-country") ||
        target.closest(".iti__country") ||
        target.closest(".iti__country-list") ||
        target.closest(".iti__search-input")
      ) {
        markManualCountrySelection();
      }
    };

    const handleKeyDown = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement | null;
      if (!target) return;
      if (event.key !== "Enter" && event.key !== " ") return;
      if (
        target.closest(".iti__selected-country") ||
        target.closest(".iti__country") ||
        target.closest(".iti__country-list")
      ) {
        markManualCountrySelection();
      }
    };

    document.addEventListener("mousedown", handlePointerDown, true);
    document.addEventListener("touchstart", handlePointerDown, true);
    document.addEventListener("keydown", handleKeyDown, true);

    return () => {
      document.removeEventListener("mousedown", handlePointerDown, true);
      document.removeEventListener("touchstart", handlePointerDown, true);
      document.removeEventListener("keydown", handleKeyDown, true);
      if (manualSelectionResetTimerRef.current !== null) {
        clearTimeout(manualSelectionResetTimerRef.current);
      }
    };
  }, [markManualCountrySelection]);

  // Keep the country dropdown fully interactive when it is portaled to <body>
  // (dropdownContainer) inside a modal Radix Dialog. While a modal Dialog is open the
  // <body> gets pointer-events:none (re-enabled for .iti--container via globals.css), and
  // Radix/react-remove-scroll attach document listeners that hijack the portaled dropdown.
  // We isolate it by class predicate (intl-tel-input owns the DOM, so there is no ref):
  // bubble-stop pointer/scroll events at <body> and guard FocusScope's focusin/focusout at
  // the document capture phase. See the hook for the full rationale. `active` is always
  // true — attaching on mount (not when the dropdown opens) avoids any race with the
  // dropdown auto-focusing its search box.
  //
  // KNOWN TRADE-OFF: this registers one set of body/document listeners per mounted
  // PhoneInput for its whole lifetime, so the `isInside` predicate (a `closest()` call)
  // runs on every page-level pointer/scroll/touch/focus event even outside dialogs.
  // intl-tel-input does emit "open:countrydropdown"/"close:countrydropdown" events that
  // could gate `active`, but the ordering of that event vs the dropdown's search-box
  // auto-focus is not verifiable outside a real browser — gating on it risks letting the
  // first focusin slip through to FocusScope, re-breaking the fix. Revisit only with an
  // E2E test covering the nested-dialog scenario.
  const isInsideItiDropdown = useCallback(
    (node: EventTarget | null) =>
      node instanceof HTMLElement
        ? !!node.closest(".iti--container, .iti__dropdown-content")
        : false,
    [],
  );
  const getBody = useCallback(
    () => (typeof document === "undefined" ? null : document.body),
    [],
  );
  useDialogPortalEventIsolation({
    active: true,
    getBubbleTarget: getBody,
    isInside: isInsideItiDropdown,
  });

  // Remove title on mount. intl-tel-input initializes asynchronously (loadUtils),
  // so we try immediately and then once more after the first animation frame to
  // ensure the flag button DOM is ready.
  useEffect(() => {
    removeFlagTitle();
    const rafId = requestAnimationFrame(removeFlagTitle);
    return () => cancelAnimationFrame(rafId);
  }, [removeFlagTitle]);

  // Build error styling
  const inputClassName = [
    "w-full h-12 rounded-xl border px-3 py-1 text-sm font-semibold",
    "focus:outline-none focus:ring-2 focus:ring-offset-0",
    error
      ? "border-none bg-destructive/10 text-destructive focus:!ring-destructive/50"
      : "border-input focus:ring-ring bg-input",
    disabled ? "cursor-not-allowed opacity-50 bg-muted text-muted-foreground" : "",
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <IntlTelInput
        ref={itiRef}
        initialValue={value || ""}
        onChangeNumber={handleNumberChange}
        onChangeCountry={handleCountryChange}
        initOptions={{
          initialCountry: safeInitialCountry as Iso2,
          // Only pass the restriction keys when set — an explicit `undefined`
          // would override the library's defaults (all countries / dropdown on).
          ...(onlyCountries && onlyCountries.length > 0
            ? { onlyCountries: onlyCountries.filter(isSupportedCountry) as Iso2[] }
            : {}),
          ...(allowDropdown === false ? { allowDropdown } : {}),
          separateDialCode: true,
          strictMode: true,
          autoPlaceholder: placeholder ? "off" : "aggressive",
          nationalMode: true,
          formatAsYouType: true,
          countrySearch: true,
          containerClass: "w-full",
          // Portal dropdown to <body> so it escapes overflow:hidden / stacking
          // contexts inside modals and dialogs (confirmed z-index regression without this).
          dropdownContainer: typeof document !== 'undefined' ? document.body : undefined,
          loadUtils: () => import("intl-tel-input/utils"),
        }}
        inputProps={{
          id,
          className: inputClassName,
          disabled,
          placeholder,
          onBlur,
          "aria-invalid": error ? "true" : undefined,
          "aria-required": required ? "true" : undefined,
        }}
      />
    );
};

export default PhoneInput;
